// complaint_page.dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:image_picker/image_picker.dart';
import 'dart:io';
import 'dart:convert';
import 'package:http/http.dart' as http;

import 'complaint_model.dart';

class ComplaintPage extends StatefulWidget {
  const ComplaintPage({super.key});

  @override
  State<ComplaintPage> createState() => _ComplaintPageState();
}

class _ComplaintPageState extends State<ComplaintPage> {
  final _formKey = GlobalKey<FormState>();
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Complaint types
  final List<String> _complaintTypes = [
    'Food Quality Issue',
    'Delivery Problem',
    'Order Missing/Incomplete',
    'Payment Issue',
    'App Technical Issue',
    'Restaurant Service',
    'Hygiene Concern',
    'Billing Problem',
    'Other'
  ];

  // Form controllers
  late TextEditingController _titleController;
  late TextEditingController _descriptionController;
  String _selectedComplaintType = 'Food Quality Issue';

  // Image handling
  List<File> _selectedImages = [];
  List<String> _uploadedImageUrls = [];
  bool _isUploading = false;
  bool _isSubmitting = false;

  // ImageKit configuration
  final String _privateApiKey = 'private_u6KRAwruwE6w8xR63Vl7enrhpzk=';
  final String _uploadEndpoint = 'https://upload.imagekit.io/api/v1/files/upload';

  @override
  void initState() {
    super.initState();
    _titleController = TextEditingController();
    _descriptionController = TextEditingController();
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _pickImages() async {
    final picker = ImagePicker();
    final pickedFiles = await picker.pickMultiImage(
      imageQuality: 80,
      maxWidth: 800,
    );

    if (pickedFiles.isNotEmpty) {
      setState(() {
        _selectedImages.addAll(pickedFiles.map((file) => File(file.path)));
      });
    }
  }

  Future<String?> _uploadImageToImageKit(File image) async {
    try {
      final bytes = await image.readAsBytes();
      final base64Image = base64Encode(bytes);

      final response = await http.post(
        Uri.parse(_uploadEndpoint),
        headers: {
          'Authorization': 'Basic ${base64Encode(utf8.encode('$_privateApiKey:'))}',
        },
        body: {
          'file': base64Image,
          'fileName': 'complaint_${DateTime.now().millisecondsSinceEpoch}.jpg',
          'useUniqueFileName': 'true',
          'folder': '/complaints', // Store in complaints folder
        },
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['url']; // Return the ImageKit URL
      } else {
        print('❌ Image upload failed: ${response.body}');
        return null;
      }
    } catch (e) {
      print('❌ Error uploading image: $e');
      return null;
    }
  }

  Future<void> _uploadAllImages() async {
    setState(() => _isUploading = true);
    _uploadedImageUrls.clear();

    for (final image in _selectedImages) {
      final imageUrl = await _uploadImageToImageKit(image);
      if (imageUrl != null) {
        _uploadedImageUrls.add(imageUrl);
      }
    }

    setState(() => _isUploading = false);
  }

  Future<Map<String, dynamic>> _getUserData() async {
    final user = _auth.currentUser;
    if (user == null) throw Exception('User not authenticated');

    // Try to get user name from address collection
    final addressDoc = await _firestore
        .collection('users')
        .doc(user.uid)
        .collection('Address')
        .doc('default')
        .get();

    String userName = 'Guest';
    if (addressDoc.exists && addressDoc['name'] != null) {
      userName = addressDoc['name'];
    } else {
      // Fallback to user document
      final userDoc = await _firestore.collection('users').doc(user.uid).get();
      if (userDoc.exists && userDoc['name'] != null) {
        userName = userDoc['name'];
      }
    }

    return {
      'userId': user.uid,
      'userName': userName,
      'userEmail': user.email ?? 'No Email',
    };
  }

  Future<void> _submitComplaint() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isSubmitting = true);

    try {
      // Upload images first
      if (_selectedImages.isNotEmpty) {
        await _uploadAllImages();
      }

      // Get user data
      final userData = await _getUserData();

      // Create complaint object
      final complaint = Complaint(
        id: '', // Will be generated by Firestore
        userId: userData['userId'],
        userName: userData['userName'],
        userEmail: userData['userEmail'],
        complaintType: _selectedComplaintType,
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim(),
        imageUrls: _uploadedImageUrls,
        status: 'Pending',
        createdAt: DateTime.now(),
      );

      // Save to Firestore
      final docRef = await _firestore
          .collection('users')
          .doc(userData['userId'])
          .collection('complaints')
          .add(complaint.toMap());

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'Complaint submitted successfully!',
            style: GoogleFonts.poppins(color: Colors.white),
          ),
          backgroundColor: Colors.green,
          duration: Duration(seconds: 3),
        ),
      );

      // Reset form
      _formKey.currentState!.reset();
      setState(() {
        _selectedImages.clear();
        _uploadedImageUrls.clear();
        _selectedComplaintType = 'Food Quality Issue';
      });

    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'Error submitting complaint: $e',
            style: GoogleFonts.poppins(color: Colors.white),
          ),
          backgroundColor: Colors.red,
        ),
      );
    } finally {
      setState(() => _isSubmitting = false);
    }
  }

  void _removeImage(int index) {
    setState(() {
      _selectedImages.removeAt(index);
    });
  }

  void _showFullScreenImage(File image) {
    showDialog(
      context: context,
      builder: (context) => Dialog(
        backgroundColor: Colors.transparent,
        child: Stack(
          children: [
            Center(
              child: Image.file(image),
            ),
            Positioned(
              top: 40,
              right: 20,
              child: IconButton(
                icon: Icon(Icons.close, color: Colors.white, size: 30),
                onPressed: () => Navigator.pop(context),
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[50],
      appBar: AppBar(
        title: Text(
          'Submit Complaint',
          style: GoogleFonts.poppins(
            fontWeight: FontWeight.w600,
            color: Colors.white,
          ),
        ),
        backgroundColor: Colors.orange[800],
        foregroundColor: Colors.white,
        elevation: 0,
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Complaint Type Dropdown
              Text(
                'Complaint Type *',
                style: GoogleFonts.poppins(
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                  color: Colors.grey[800],
                ),
              ),
              const SizedBox(height: 8),
              Container(
                width: double.infinity,
                padding: const EdgeInsets.symmetric(horizontal: 16),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.grey[300]!),
                ),
                child: DropdownButtonHideUnderline(
                  child: DropdownButton<String>(
                    value: _selectedComplaintType,
                    isExpanded: true,
                    icon: Icon(Icons.arrow_drop_down, color: Colors.orange[800]),
                    style: GoogleFonts.poppins(
                      fontSize: 16,
                      color: Colors.grey[800],
                    ),
                    onChanged: (String? newValue) {
                      setState(() {
                        _selectedComplaintType = newValue!;
                      });
                    },
                    items: _complaintTypes.map<DropdownMenuItem<String>>((String value) {
                      return DropdownMenuItem<String>(
                        value: value,
                        child: Text(value),
                      );
                    }).toList(),
                  ),
                ),
              ),
              const SizedBox(height: 20),

              // Title Field
              TextFormField(
                controller: _titleController,
                decoration: InputDecoration(
                  labelText: 'Complaint Title *',
                  labelStyle: GoogleFonts.poppins(),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: BorderSide(color: Colors.orange[800]!),
                  ),
                  prefixIcon: Icon(Icons.title, color: Colors.orange[800]),
                ),
                style: GoogleFonts.poppins(),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter a title for your complaint';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 20),

              // Description Field
              TextFormField(
                controller: _descriptionController,
                maxLines: 5,
                decoration: InputDecoration(
                  labelText: 'Description *',
                  labelStyle: GoogleFonts.poppins(),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: BorderSide(color: Colors.orange[800]!),
                  ),
                  alignLabelWithHint: true,
                  prefixIcon: Icon(Icons.description, color: Colors.orange[800]),
                ),
                style: GoogleFonts.poppins(),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please describe your complaint';
                  }
                  if (value.trim().length < 10) {
                    return 'Description should be at least 10 characters long';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 20),

              // Image Upload Section
              Row(
                children: [
                  Text(
                    'Attach Images',
                    style: GoogleFonts.poppins(
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                      color: Colors.grey[800],
                    ),
                  ),
                  const SizedBox(width: 8),
                  Text(
                    '(Optional)',
                    style: GoogleFonts.poppins(
                      fontSize: 14,
                      color: Colors.grey[600],
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 8),
              Text(
                'Add photos to help us understand your issue better',
                style: GoogleFonts.poppins(
                  fontSize: 12,
                  color: Colors.grey[600],
                ),
              ),
              const SizedBox(height: 12),

              // Image Picker Button
              SizedBox(
                width: double.infinity,
                child: ElevatedButton.icon(
                  onPressed: _isUploading ? null : _pickImages,
                  icon: Icon(Icons.camera_alt_outlined),
                  label: Text('Select Images from Gallery'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.orange[50],
                    foregroundColor: Colors.orange[800],
                    padding: EdgeInsets.symmetric(vertical: 12),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                      side: BorderSide(color: Colors.orange[300]!),
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Selected Images Grid
              if (_selectedImages.isNotEmpty) ...[
                Text(
                  'Selected Images (${_selectedImages.length})',
                  style: GoogleFonts.poppins(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: Colors.grey[700],
                  ),
                ),
                const SizedBox(height: 8),
                GridView.builder(
                  shrinkWrap: true,
                  physics: NeverScrollableScrollPhysics(),
                  gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 3,
                    crossAxisSpacing: 8,
                    mainAxisSpacing: 8,
                    childAspectRatio: 1,
                  ),
                  itemCount: _selectedImages.length,
                  itemBuilder: (context, index) {
                    return Stack(
                      children: [
                        GestureDetector(
                          onTap: () => _showFullScreenImage(_selectedImages[index]),
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(8),
                              image: DecorationImage(
                                image: FileImage(_selectedImages[index]),
                                fit: BoxFit.cover,
                              ),
                            ),
                          ),
                        ),
                        Positioned(
                          top: 4,
                          right: 4,
                          child: GestureDetector(
                            onTap: () => _removeImage(index),
                            child: Container(
                              padding: EdgeInsets.all(4),
                              decoration: BoxDecoration(
                                color: Colors.red,
                                shape: BoxShape.circle,
                              ),
                              child: Icon(
                                Icons.close,
                                color: Colors.white,
                                size: 16,
                              ),
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
                const SizedBox(height: 16),
              ],

              // Uploading Indicator
              if (_isUploading) ...[
                Center(
                  child: Column(
                    children: [
                      CircularProgressIndicator(color: Colors.orange[800]),
                      const SizedBox(height: 8),
                      Text(
                        'Uploading images...',
                        style: GoogleFonts.poppins(
                          fontSize: 14,
                          color: Colors.grey[600],
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 16),
              ],

              // Submit Button
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _isSubmitting ? null : _submitComplaint,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.orange[800],
                    foregroundColor: Colors.white,
                    padding: EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    elevation: 4,
                  ),
                  child: _isSubmitting
                      ? SizedBox(
                    width: 20,
                    height: 20,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                    ),
                  )
                      : Text(
                    'Submit Complaint',
                    style: GoogleFonts.poppins(
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 20),

              // Info Text
              Container(
                width: double.infinity,
                padding: EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.blue[50],
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.blue[100]!),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.info_outline, color: Colors.blue[800], size: 20),
                        const SizedBox(width: 8),
                        Text(
                          'What happens next?',
                          style: GoogleFonts.poppins(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                            color: Colors.blue[800],
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Text(
                      '• Your complaint will be reviewed within 24 hours\n'
                          '• You will receive updates via email\n'
                          '• Our support team may contact you for more details\n'
                          '• Typical resolution time: 2-3 business days',
                      style: GoogleFonts.poppins(
                        fontSize: 12,
                        color: Colors.blue[700],
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}